version: "3.8"
services:
  node-app:
    build:
      context: ./app
    container_name: node-app
    ports:
      - "3000:3000" # Exponer el puerto 3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase # Variable de entorno para conectar a MongoDB
    depends_on:
      - mongo # Asegurar que MongoDB esté listo antes de iniciar

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017" # Exponer el puerto 27017
    volumes:
      - mongo-data:/data/db # Persistir datos de MongoDB

volumes:
  mongo-data: