apiVersion: v1                     # Versión de la API de Kubernetes para el recurso Service.
kind: Service                      # Especifica que se está creando un Service.
metadata:
  name: node-app-service           # Nombre del Service.
  namespace: node-app-namespace    # Namespace donde se desplegará el Service.
spec:
  selector:
    app: node-app                  # Selector que identifica los pods a los que el Service enviará el tráfico. 
  ports:
    - protocol: TCP                # Protocolo utilizado para el tráfico (TCP).
      port: 30000                  # Puerto expuesto por el Service para acceder externamente.
      targetPort: 3000             # Puerto en el contenedor donde la aplicación escucha las solicitudes.
  type: LoadBalancer               # Tipo de Service que expone la aplicación a través de un balanceador de carga externo.
