apiVersion: v1                 # Versión de la API de Kubernetes para el recurso Service.
kind: Service                  # Especifica que se está creando un Service.
metadata:
  name: mongo-service          # Nombre del Service. Se utiliza para acceder a MongoDB dentro del clúster.
  namespace: node-app-namespace  # Namespace donde se desplegará el Service.
spec:
  selector:
    app: mongo                 # Selector que identifica los pods a los que el Service enviará el tráfico.
                               # Debe coincidir con la etiqueta `app: mongo` en el Deployment de MongoDB.
  ports:
    - port: 27017              # Puerto en el que el Service escucha las solicitudes.
      targetPort: 27017        # Puerto en el contenedor de MongoDB al que se redirige el tráfico.
  type: ClusterIP              # El tipo de Service.
                               # `ClusterIP` permite el acceso interno dentro del clúster (no accesible desde fuera).
