apiVersion: v1
kind: Service
metadata:
  name: mongo-service   # Debe coincidir con el nombre en la variable MONGO_URL
  namespace: node-app-namespace
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
